name: Terraform

on:
  pull_request:
    branches:
      - 'master'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.6.6"

    - run: terraform init

    - run: terraform validate
